package com.zh.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBGROUP_LAST_CHAT_LOG".
 */
public class DBGroupLastChatLog {

    private Long id;
    private String sendTime;
    private String sessonGroupName;
    private String sendWeiXinName;
    private String sendWeiXinNickName;
    private String sendContent;
    private Integer sendContentType;

    public DBGroupLastChatLog() {
    }

    public DBGroupLastChatLog(Long id) {
        this.id = id;
    }

    public DBGroupLastChatLog(Long id, String sendTime, String sessonGroupName, String sendWeiXinName, String sendWeiXinNickName, String sendContent, Integer sendContentType) {
        this.id = id;
        this.sendTime = sendTime;
        this.sessonGroupName = sessonGroupName;
        this.sendWeiXinName = sendWeiXinName;
        this.sendWeiXinNickName = sendWeiXinNickName;
        this.sendContent = sendContent;
        this.sendContentType = sendContentType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSendTime() {
        return sendTime;
    }

    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    public String getSessonGroupName() {
        return sessonGroupName;
    }

    public void setSessonGroupName(String sessonGroupName) {
        this.sessonGroupName = sessonGroupName;
    }

    public String getSendWeiXinName() {
        return sendWeiXinName;
    }

    public void setSendWeiXinName(String sendWeiXinName) {
        this.sendWeiXinName = sendWeiXinName;
    }

    public String getSendWeiXinNickName() {
        return sendWeiXinNickName;
    }

    public void setSendWeiXinNickName(String sendWeiXinNickName) {
        this.sendWeiXinNickName = sendWeiXinNickName;
    }

    public String getSendContent() {
        return sendContent;
    }

    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }

    public Integer getSendContentType() {
        return sendContentType;
    }

    public void setSendContentType(Integer sendContentType) {
        this.sendContentType = sendContentType;
    }

}
