package com.zh.data.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBUSER".
*/
public class DBUserDao extends AbstractDao<DBUser, Long> {

    public static final String TABLENAME = "DBUSER";

    /**
     * Properties of entity DBUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property SessonGroupName = new Property(1, String.class, "sessonGroupName", false, "SESSON_GROUP_NAME");
        public final static Property WeiXinName = new Property(2, String.class, "weiXinName", false, "WEI_XIN_NAME");
        public final static Property WeixinNickName = new Property(3, String.class, "weixinNickName", false, "WEIXIN_NICK_NAME");
    };


    public DBUserDao(DaoConfig config) {
        super(config);
    }
    
    public DBUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBUSER\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SESSON_GROUP_NAME\" TEXT," + // 1: sessonGroupName
                "\"WEI_XIN_NAME\" TEXT," + // 2: weiXinName
                "\"WEIXIN_NICK_NAME\" TEXT);"); // 3: weixinNickName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBUSER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBUser entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sessonGroupName = entity.getSessonGroupName();
        if (sessonGroupName != null) {
            stmt.bindString(2, sessonGroupName);
        }
 
        String weiXinName = entity.getWeiXinName();
        if (weiXinName != null) {
            stmt.bindString(3, weiXinName);
        }
 
        String weixinNickName = entity.getWeixinNickName();
        if (weixinNickName != null) {
            stmt.bindString(4, weixinNickName);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBUser readEntity(Cursor cursor, int offset) {
        DBUser entity = new DBUser( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sessonGroupName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // weiXinName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // weixinNickName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBUser entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSessonGroupName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeiXinName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWeixinNickName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBUser entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBUser entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
