package com.zh.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBUSER".
 */
public class DBUser {

    private Long id;
    private String sessonGroupName;
    private String weiXinName;
    private String weixinNickName;

    public DBUser() {
    }

    public DBUser(Long id) {
        this.id = id;
    }

    public DBUser(Long id, String sessonGroupName, String weiXinName, String weixinNickName) {
        this.id = id;
        this.sessonGroupName = sessonGroupName;
        this.weiXinName = weiXinName;
        this.weixinNickName = weixinNickName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSessonGroupName() {
        return sessonGroupName;
    }

    public void setSessonGroupName(String sessonGroupName) {
        this.sessonGroupName = sessonGroupName;
    }

    public String getWeiXinName() {
        return weiXinName;
    }

    public void setWeiXinName(String weiXinName) {
        this.weiXinName = weiXinName;
    }

    public String getWeixinNickName() {
        return weixinNickName;
    }

    public void setWeixinNickName(String weixinNickName) {
        this.weixinNickName = weixinNickName;
    }

}
